export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const TEAM_SUCCESS = "TEAM_SUCCESS";
